OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=2 python3 ./ood_maha.py \
--model ResNet18Gram \
--dataset cifar10 \
--name cifar_hvcm \
--ind_path data \
--ood_path data \
--num_classes 10 \
--batch_size 128 \
--saveroot results \
--attri_dim 1024 \
--num_kernel 32